/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_tamu_lenss_mdfs_crypto_ReedSolomon */

#ifndef _Included_edu_tamu_lenss_mdfs_crypto_ReedSolomon
#define _Included_edu_tamu_lenss_mdfs_crypto_ReedSolomon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_tamu_lenss_mdfs_crypto_ReedSolomon
 * Method:    decode
 * Signature: ([[B[[B[I[IJIIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_tamu_lenss_mdfs_crypto_ReedSolomon_decode
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jintArray, jintArray, jlong, jint, jint, jint, jint);

/*
 * Class:     edu_tamu_lenss_mdfs_crypto_ReedSolomon
 * Method:    encode
 * Signature: ([BIII)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_edu_tamu_lenss_mdfs_crypto_ReedSolomon_encode
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     edu_tamu_lenss_mdfs_crypto_ReedSolomon
 * Method:    dummyCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_tamu_lenss_mdfs_crypto_ReedSolomon_dummyCall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
